// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wxeyfpywxuselszycuag.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Ind4ZXlmcHl3eHVzZWxzenljdWFnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5MDE5NjQsImV4cCI6MjA2NTQ3Nzk2NH0.6zkMI0NrDqrfeZeRsAJGZTXDs3BSvrrSB4m1E2REwC8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});